### ISSUE TITLE
privilege issues with admin

### ISSUE THREAD

**Issue by ckot** [leandigo/django-oneall#16]
**EDIT**:
python 2.7.6
Django 1.8.12
django-oneall 1.1.2

Using django-oneall for admin login logs the user in just fine, but for some reason the user doesn't have any of their privileges.   I'm merely assigning privs to Groups, and assigning Users to Groups, I haven't tried setting privs for individual users, to know if it's only the group privs, or all privs that are missing.

Of course everything works fine if I `setsuperuser` my user, but you shouldn't need to be a superuser to user the admin, merely `staff` and have privs to do things.  Anyway, I can't be using `setsuperuser` to get admin access as different staff users have different privs, and I don't want them to automatically have all privs.

I haven't dug into Django's source code, but I'm wondering if the privs are cached along with the User in the session or something, rather than looking them up at each request.  Perhaps, they need to be associated to the User object prior to returning it from an authentication function?  Just a wild guess...

**Comment by ckot** [comment]
The following change to `auth.py` _seems_ to fix the issue regarding permissions:

```
#class BaseBackend(object):
class BaseBackend(ModelBackend):
    def __init__(self, existing_user=None):
        self.user = existing_user

    # @classmethod
    # def get_user(cls, user_id):
    #     """
    #     Retrieve user by user ID
    #     :param user_id: User ID
    #     """
    #     return ModelBackend().get_user(user_id)
```

I'm thinking that by simply subclassing `ModelBackend` and merely overriding the methods you need to, means you don't need to implement the all the accessor methods for user and group privileges.  I haven't looked deeper into the Django code, so it's still a black box to me, but based on the behavior, but I'm guessing that it _might_ be doing a hasattr for these privilege related accessor methods, and if not found, simply returning an empty set or something like that.

**Comment by ckot** [comment]
I've added PR #18 which fixes this

**Comment by Liz4v** [comment]
Version 1.2 published to PyPI includes this fix.
