### ISSUE TITLE
'oneall' is not a valid tag library

### ISSUE THREAD

**Issue by mlcrazy** [leandigo/django-oneall#19]
TemplateSyntaxError: 'oneall' is not a valid tag library: ImportError raised loading django_oneall.templatetags.oneall: cannot import name get_user_model

django==1.8.11
django_oneall==1.2
pyoneall==0.2.3

I'm set this up per the samples from the django_oneall and pyoneall configuration docs and am getting this error on the django_oneall login.html template.  Seems to be similar to #15 but in django_oneall 1.2

**Comment by mlcrazy** [comment]
/venv/lib/python2.7/site-packages/django_oneall/templates/oneall/login.html, error at line 7

**Comment by ckot** [comment]
I was about to report this one as well, but haven't had time.  The issue is that get_user_model()
needs to be included from django.contrib.auth instead of django.db.models. 

Hopefully the bad import path isn't due to my PR for #15

**Comment by Liz4v** [comment]
There was a fork that switched from one to the other. I got intrigued, tested both, and both worked. I looked for documentation, and only one of them was used, the other was unmentioned. This feels like an undocumented move of that function.

**Comment by ckot** [comment]
hmm that sucks.  I suppose the fix would be to do a try/except for the import of that function

**Comment by Liz4v** [comment]
I already found two other unrelated bugs trying to reproduce this one. :( This project needs a new maintainer who is actually still using it.

**Comment by Liz4v** [comment]
I wasn't able to reproduce before or after 19429f9e99f008d3afd18526b184fd1327bd5b6c. I'm pushing a new version nonetheless, because I confirmed that newer versions of django do not work with the old `django.db.models` package.

**Comment by Liz4v** [comment]
@mlcrazy Please retry with [latest release](https://pypi.python.org/pypi/django-oneall/1.2.2) and let us know.

**Comment by Liz4v** [comment]
Marking this issue resolved as of commit 19429f9e99f008d3afd18526b184fd1327bd5b6c, included in release [1.2.2](https://pypi.python.org/pypi/django-oneall/1.2.2). Please provide full stack if still having problems.
