### ISSUE TITLE
question: any ETA on the development branch?

### ISSUE THREAD

**Issue by ckot** [leandigo/django-oneall#2]
I was just working on changes to get this to work on django > 1.6 as well as python3, and noticed that the development branch has made such changes already.  Your changes look better than mine, as I'm neither as familiar with django, oneall, or python3, so I'd much rather use yours (all I know is that my changes make it possible to `python manage.py migrate` without errors popping up anymore). Any ETA on when this will be ready?

**Comment by Liz4v** [comment]
I must test it against Python 2 before I can mark it stable. It should be
this month, but I'm having Internet trouble, so I'm not comfortable giving
an ETA. But if you're on Python 3, it should be good to go. Just make sure
you also grab pyoneall on the development branch as well.

**Comment by ckot** [comment]
Hmm.  I'm having some issues.   I forked both the `pyoneall` and `django_oneall repos`, and did a `python setup.py install`  on the `develop` branch of each of them.  Here are the problems I bumped into:

First off, although this is a `pyoneall` thing, it should be noted that it depends on the `future` package being installed.  Furthermore, that package doesn't work with python 3.2, so your requirements are python>=3.3 at least  (I compiled my own python3.4 to get around this).

After that I got the following error:
`ValueError: attempted relative import beyond top-level package`

which had to do with `models.py`

```
from ..base import OADict
```

needing to be changed to:

```
from pyoneall.base import OADict
```

and in `auth.py`:

```
from ..connection import OneAll
```

needed to be changed to:

```
from pyoneall.connection import OneAll
```

now I'm getting:

```
Error during template rendering
In template /home/ckot/dev/tutalk_admin/templates/oneall/login.html, error at line 5
{% load oneall %}
Exception Type: TemplateSyntaxError
Exception Value:    'oneall' is not a valid tag library: Template library oneall not found, tried django.templatetags.oneall,django.contrib.admin.templatetags.oneall,django.contrib.staticfiles.templatetags.oneall,rest_framework.templatetags.oneall
```

I noticed the following files were missing, so I created (empty):

```
django_oneall/__init__.py
django_oneall/templatetags/__init__.py
```

Hoping that it would fix the `{ %l oad oneall %}` issue, but I'm still getting the same exact error.  I'm puzzled why it i isn't searching in `django_oneall.templatetags.oneall` as I _do_ have `django_oneall` in `INSTALLED_APPS`

Any idea why it isn't finding the `oneall` templatetags?

**Comment by ckot** [comment]
ok, I did some plugging around and made some more changes:

first I noticed that none of the sub-packages were being installed (thus no templatetags dir) so I modified setup.py

```
from setuptools import setup, find_packages

....

packages=find_packages(),
```

and to make sure the `templates` directory gets installed:

```
package_data={
    'django_oneall/templates/oneall': [
        'header.html', 
        'login.html',
        'profile.html',
        'social_login.html'
    ]
},
include_package_data=True,
```

and MANIFEST.in

```
include django_oneall/templates/oneall/*.html
```

this allowed the login page to display, and I was able to login using my google account, but when it returned I get the following error.

```
Traceback:
File "/home/ckot/venvs/p3.4d1.8/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
 132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/ckot/venvs/p3.4d1.8/lib/python3.4/site-packages/django/views/decorators/csrf.py" in wrapped_view
 58.         return view_func(*args, **kwargs)
File "/home/ckot/dev/django-oneall/django_oneall/views.py" in oa_login
 56.         user = authenticate(**auth_with)
File "/home/ckot/venvs/p3.4d1.8/lib/python3.4/site-packages/django/contrib/auth/__init__.py" in authenticate
 74.             user = backend.authenticate(**credentials)
File "/home/ckot/dev/django-oneall/django_oneall/auth.py" in authenticate
 41.         oa_user = oneall.connection(connection_token).user
File "/home/ckot/dev/pyoneall/pyoneall/connection.py" in connection
  138.         response = OADict(**self._exec('connection/%s' % (connection_token))).response
File "/home/ckot/dev/pyoneall/pyoneall/connection.py" in _exec
  46.         auth = encodestring('%s:%s' % (self.public_key, self.private_key)).replace('\n', '')
File "/home/ckot/venvs/p3.4d1.8/lib/python3.4/base64.py" in encodestring
  548.     return encodebytes(s)
File "/home/ckot/venvs/p3.4d1.8/lib/python3.4/base64.py" in encodebytes
  536.     _input_type_check(s)
File "/home/ckot/venvs/p3.4d1.8/lib/python3.4/base64.py" in _input_type_check
  522.         raise TypeError(msg) from err

Exception Type: TypeError at /oneall/login
Exception Value: expected bytes-like object, not str
```

Unfortunately, this might take me a bit longer to debug.  Any idea what's going wrong?

BTW, you must have explicity deleted the `django_oneall/__init__.py`, and didn't put one in the templatetags dir -  are you using namespaced packaging or something?  If so, I found that there is an issue with `setuptools::find_packages()` not automatically finding packages which don't have an **init**.py, meaning that you need to list them all explicitly in `packages`

**Comment by Liz4v** [comment]
Please submit these changes you described as a pull request.

Explicitly deleting `__init__.py` is supposed to be allowed under py3.4 (which was my only target when I made my improvements) and has been working fine for me, but since py2 doesn't like it they'll have to come back anyway.

This bytes bug is typical 2to3 trouble. Try commit da6960312cfa8a601ceff1a4a7378384f1a372ef.

**Edit:** [I've just created a tag for it.](https://github.com/leandigo/django-oneall/tree/py3.4-standalone)

**Comment by ckot** [comment]
ok.  i've submit PRs for both `django-oneall` and `pyoneall`

now I just have to figure out how to actually use the package.  I knew how to use the old pyoneall, but I'm new to django, and don't know where to put my code to create a new user if the `auth_token` isn't in the `auth_users table`... :(  I'm guessing I need to add a view somewhere, but _where_....

**Comment by Liz4v** [comment]
Thanks! I'll review it as soon as I'm able.

The users are created automatically by the auth module. That's part of the spirit of social authentication. 😉

**Comment by Liz4v** [comment]
ETA: Sept 25. ;)
