### ISSUE TITLE
issue when upgrading to Django 10+ when using 'store_user_info': False feature

### ISSUE THREAD

**Issue by ckot** [leandigo/django-oneall#21]
Django 1.10 up'd the length of auth_User.username from 30 to 150 chars.   

This is fine for new users and/or new installations, but it causes existing users prior to an upgrade to be mis-identified.

I could put together a PR to fix this - just wanted some feedback first

I was thinking of simply adding another config option (only relevant for the pseudorandom usernames), such as 'pre_django1_10_usernames' (default=False) , and it's set to True simply use 30 chars instead of getting the username field length from the User models meta data.  

The logic seems really simple, I imagine the main part is agreeing on the option name for the config.

-Scott

**Comment by Liz4v** [comment]
I would suggest having geared to that specific change instead, such as "max_username_length": 150.

If it's possible to infer the default from the result of get_user_model() that's even better.

**Comment by ckot** [comment]
wow! quick response!

I'm glad I consulted you prior to my PR.  'max_username_length': (default 150) sounds much better.  

And yes you have existing code which gets the max_length of the field via  get_user_model() - It will be simple to compare the option's value to that to determine if it's sane.

**Comment by Liz4v** [comment]
Fixed by pull request #22, included in release 1.3. Thank you!
