### ISSUE TITLE
getting HTTP Error 401 Unauthorized

### ISSUE THREAD

**Issue by ckot** [leandigo/django-oneall#4]
NVM, it took me 5 hours, but I discovered that I had my `ONEALL_PUBLIC_KEY` and `ONEALL_PRIVATE_KEY` reversed.

**Comment by Liz4v** [comment]
Two questions: is your subdomain just your subdomain (correct) or the full OneAll URL for your subdomain (incorrect)? Second question, is localhost in your whitelist?

It's not too clear to me if OneAll issued that 401 from their side into the authentication module. It sort of looks like this is the case. These are the configurations to check (aside from your keys, of course).

**Comment by ckot** [comment]
yeah, I had everything else configured right. just the subdomain and I had localhost whitelisted.  just a stupid error in my settings.py.  I even compared the keys character per character but didn't notice that I had them assigned to the wrong bars :(.  I deleted the original comments so as not to confuse any others who may find this on a search or something.

**Comment by Liz4v** [comment]
I originally had the same problem. :( I'll ask upstream.

Edit: [Link!](https://support.oneall.com/forums/discussion/2131/is-there-a-way-to-detect-whether-the-public-and-private-key-are-swapped)

**Comment by ckot** [comment]
BTW.  I never would have figured it out if not for `httpie` having a `--print` option or `curl` having a `-v` option where they output the request headers and I saw that the base64 encoded auth tokens were  drastically different from what my app was producing, but both tools spit out the exact same header...
